name: helm lint

on:
  push:
    branches:
      - master

jobs:
  lint-and-publish:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch history
        run: git fetch --prune --unshallow
      - uses: azure/setup-helm@v1
      - name: lint
        run: |
          helm version
          helm lint .
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Package the chart
        run: |
          helm package . --destination .release-packages --dependency-update
          version=$(grep 'version:' Chart.yaml| awk '{print $2}')
          echo "::set-env name=VERSION::$version"
      - name: Make the release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ VERSION }}
          release_name: "this is a test"
          body: "this is the test of the body"

