name: helm lint

on:
  push:
    branches:
      - master

jobs:
  lint-and-publish:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch history
        run: git fetch --prune --unshallow
      - uses: azure/setup-helm@v1
      - name: lint
        run: |
          helm version
          helm lint .
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Package the chart
        run: |
          helm package . --destination .cr-release-packages --dependency-update
      - name: Install chart releaser
        run: |
          version=v1.0.0-beta.1
          curl -sSLo cr.tar.gz "https://github.com/helm/chart-releaser/releases/download/$version/chart-releaser_${version#v}_linux_amd64.tar.gz"
          tar -xzf cr.tar.gz
          sudo mv cr /usr/local/bin/cr
      - name: release the chart
        run: |
          cr upload -o "underscorgan" -r "puppetserver-helm-chart" -t "$GITHUB_TOKEN"
          mkdir .cr-index
          cr index -o "underscorgan" -r "puppetserver-helm-chart" -c "https://underscorgan.github.io/puppetserver-helm-chart" -t "$GITHUB_TOKEN"
          gh_pages_worktree=$(mktemp -d)
          git worktree add "$gh_pages_worktree" gh-pages
          cp --force .cr-index/index.yaml "$gh_pages_worktree/index.yaml"
          pushd "$gh_pages_worktree" > /dev/null
          git add index.yaml
          git commit --message="Update index.yaml" --signoff
          local repo_url="https://x-access-token:$GITHUB_TOKEN@github.com/underscorgan/puppetserver-helm-chart"
          git push "$repo_url" gh-pages
          popd > /dev/null
